# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wistia-api 0.2.4 ruby lib

Gem::Specification.new do |s|
  s.name = "wistia-api"
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeff Vincent", "Jim Bancroft", "Mark Bates", "Robby Grossman"]
  s.date = "2017-10-27"
  s.description = "A ruby library for working with Wistia's data API."
  s.email = "support@wistia.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/wistia.rb",
    "lib/wistia/base.rb",
    "lib/wistia/config.rb",
    "lib/wistia/initialization.rb",
    "lib/wistia/media.rb",
    "lib/wistia/medias/caption.rb",
    "lib/wistia/project.rb",
    "lib/wistia/projects/sharing.rb",
    "lib/wistia/stats.rb",
    "spec/spec_helper.rb",
    "spec/support/config.test.yml",
    "spec/support/h.srt",
    "spec/wistia/base_spec.rb",
    "spec/wistia/config_spec.rb",
    "spec/wistia/media_spec.rb",
    "spec/wistia/medias/caption_spec.rb",
    "spec/wistia/project_spec.rb",
    "spec/wistia/projects/sharing_spec.rb",
    "spec/wistia/stats_spec.rb",
    "wistia-api.gemspec"
  ]
  s.homepage = "http://github.com/wistia/wistia-api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Ruby wrapper for Wistia's API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, [">= 2.3.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12"])
    else
      s.add_dependency(%q<activeresource>, [">= 2.3.8"])
      s.add_dependency(%q<bundler>, ["~> 1.2"])
      s.add_dependency(%q<fakeweb>, ["~> 1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.12"])
    end
  else
    s.add_dependency(%q<activeresource>, [">= 2.3.8"])
    s.add_dependency(%q<bundler>, ["~> 1.2"])
    s.add_dependency(%q<fakeweb>, ["~> 1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.12"])
  end
end

